SPAWN_RED_RADIUS = 25
SPAWN_GREEN_RADIUS = 40

MAX_PEDS = 16
MAX_PEDS_PER_SPAWN = 2
CHECK_TIME_SPAWN = 200
CHECK_TIME_RELEASE = 900
CHECK_TIME_PED_KEYS = 700
CHECK_TIME_PED_STATE = 100

MIN_DISTANCE_TO_NODE = 1.5
