SPAWN_RED_RADIUS = 25
SPAWN_GREEN_RADIUS = 40

MAX_PEDS = 16
MAX_PEDS_PER_SPAWN = 2
CHECK_TIME_SPAWN = 200
CHECK_TIME_RELEASE = 900
CHECK_TIME_PED_KEYS = 200
CHECK_TIME_PED_STATE = 100

PED_ROTATION_SPEED = 200           -- deg per second
PED_WAIT_TIME = 500
PED_GO_AROUND_TIME = 600
PED_DEATH_REMOVE = 1500             -- remove ped after death

MIN_DISTANCE_TO_NODE = 2
